# Introduction to Numpy and Numba
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

## Numpy Arrays

In [1]:
# We always import Numpy as follows in order not to pollute the namespace
import numpy as np

In [2]:
# central to Numpy is a special array type 
# to create it we passs a Python list
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


In [3]:
# We can also pass in a 2 dimensional Python list to create a 2D array
m = np.array([[1, 2, 5], [4, 3, 4]])
print(m)

[[1 2 5]
 [4 3 4]]


In [4]:
print(type(m)) 

<class 'numpy.ndarray'>


In [5]:
v.shape

(4,)

In [6]:
m.shape

(2, 3)

In [7]:
v.size

4

In [8]:
m.size

6

In [9]:
# Accessing is same as in Python arrays
m[1][2]

4

In [10]:
# But we can ALSO access the elements using a shorter notation
m[1,2]

4

In [11]:
# We can change the shape of an array
v.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [12]:
# We can create large arrays of zeros
z = np.zeros(100)

In [13]:
print(z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [14]:
# We can add some shape to the matrix using a tuple containing the number of rows and columns
z = np.zeros((5,10))
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [15]:
# If we want to start with ones
z = np.ones(20)
print(z)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]


In [16]:
z = np.ones((5,4))
print(z)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


## Arange

In [17]:
# Numpy has its own range function called arange
l = np.arange(10)
print(l)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# We can shuffle the order of the array - note that shuffle changes it
np.random.shuffle(l)
print(l)

[5 1 2 3 4 7 9 8 6 0]


## Element-wise Array Functions
Standard mathematical operations act on the elements of an array

In [19]:
# Create a matrix to begin with
m = np.array([[4,2,6],[9,4,6],[2,3,1]])
print(m)

[[4 2 6]
 [9 4 6]
 [2 3 1]]


In [20]:
# Extracting sub arrays - extract all in column 3 (2 == column 3)
m[:,2]

array([6, 6, 1])

In [21]:
# Extracting sub arrays - extract all in row 3 (1 == row 2)
m[1,:]

array([9, 4, 6])

In [22]:
print(m*2)

[[ 8  4 12]
 [18  8 12]
 [ 4  6  2]]


In [23]:
# This is NOT matrix multiplication. It is elementwise squaring
print(m*m)

[[16  4 36]
 [81 16 36]
 [ 4  9  1]]


In [24]:
# Can do elementwise tests that return booleans
c = m > 3.0
print(c)

[[ True False  True]
 [ True  True  True]
 [False False False]]


## Matrix Operations

In [25]:
# Create an identity matrix that must be a square matrix
i = np.identity(5)
print(i)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [26]:
m=np.array([[2,3],[1,4]])

In [27]:
# Transpose of a matrix is when columns and rows are swapped
print(m)

[[2 3]
 [1 4]]


In [28]:
# Matrix multiplication m x m
m.dot(m)

array([[ 7, 18],
       [ 6, 19]])

In [29]:
# Average
m.mean()

2.5

In [30]:
# Variance
m.var()

1.25

In [31]:
# Calculate matrix inverse 
inv = np.linalg.inv(m)

In [32]:
# Check that this gives the identity when multiplied 
inv.dot(m)

array([[ 1.,  0.],
       [ 0.,  1.]])

## Random Numbers in Numpy

In [33]:
# uniform random numbers in [0,1]
r=np.random.rand(5,5)
print(r)

[[ 0.93338501  0.13502526  0.75622156  0.96468419  0.15211264]
 [ 0.38864859  0.61991793  0.47862712  0.91972276  0.94341776]
 [ 0.79847464  0.98101109  0.67698323  0.8579498   0.45078548]
 [ 0.92466121  0.37019181  0.94566424  0.21686766  0.38245885]
 [ 0.60058738  0.75375993  0.67266628  0.58262956  0.70865469]]


In [34]:
# Gaussian random numbers 
r=np.random.normal(size=(5,5))
print(r)

[[ 0.54644314  1.15778295  0.0933669   1.0034846  -0.07948764]
 [ 0.66468787  0.73745751 -0.24611901 -0.9770605  -0.31713389]
 [-1.41973709  0.72862815 -0.10404896  0.85579236 -1.14951215]
 [ 0.78392578  1.88197637  0.23193216 -0.27760288 -1.15103398]
 [ 1.38041802  0.92808022  0.75479893 -1.86551171  1.07212943]]


## Vectorized Calculations

In [35]:
import timeit

In [36]:
# Do not use Python math functions with Numpy - this fails
from math import exp

In [37]:
numElements = 10000
rarray=np.random.rand(numElements)

In [38]:
def f1(rv):
    x=[]
    for r in rarray: x.append(exp(r))
    return x

In [39]:
%timeit x = f1(rarray)

3.25 ms ± 316 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


A ms is a thousandth of a second

In [40]:
x = f1(rarray)

In [41]:
t1 = 2.73*0.001

In [42]:
print(x[2929])

2.648310244684329


In [43]:
def f2(rv):
    x=np.exp(rv)
    return x

In [44]:
%timeit x = f2(rarray)

105 µs ± 9.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


A $\mu$ second is a millionth of a second

In [45]:
t2 = 80.9 * 0.000001

In [46]:
x = f2(rarray)

In [47]:
print(x[2929])

2.64831024468


In [48]:
t1/t2

33.74536464771323

I get a factor of improvement of about 34

# Numba

In [49]:
from numba import jit, float32

In [50]:
@jit
def f3(rv):
    x = []
    for r in rv: 
        x.append(exp(r))
 
    return x

In [51]:
x = f3(rarray)

In [52]:
print(x[2929])

2.648310244684329


In [53]:
%timeit f3(rarray)

615 µs ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
t3 = 351*0.000001

In [55]:
print("Basic Python %9.5f ms" %(t1*1000000))
print("Numpy Python %9.5f ms" %(t2*1000000))
print("Numba Python %9.5f ms" %(t3*1000000))

Basic Python 2730.00000 ms
Numpy Python  80.90000 ms
Numba Python 351.00000 ms


## Using Numba if the function cannot be vectorized

In [56]:
from numba import jit

In [57]:
def basicSort1(x):
    n = len(x)
    ordered = False
    
    while ordered == False:
        ordered = True

        for i in range(0,n-1):
            if x[i+1] < x[i]:
                a = x[i]
                x[i] = x[i+1]
                x[i+1] = a
                ordered = False

In [58]:
@jit 

def basicSort2(x):
    n = len(x)
    ordered = False
    
    while ordered == False:
        ordered = True

        for i in range(0,n-1):
            if x[i+1] < x[i]:
                a = x[i]
                x[i] = x[i+1]
                x[i+1] = a
                ordered = False

In [62]:
# Do not make this too large as computational time scales as this squared
numElements = 1000

In [63]:
v = np.arange(0,numElements)
np.random.shuffle(v)

In [64]:
%timeit basicSort1(v);

453 µs ± 23.1 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [65]:
v = np.arange(0,numElements)
np.random.shuffle(v)

In [66]:
% timeit basicSort2(v);

1.92 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [68]:
453/1.92

235.9375

Once again we get a big speed up